name: rain_alert
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies (versões estáveis e compatíveis)
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.4

  # State management
  provider: ^6.0.5

  # Geolocation
  geolocator: ^13.0.1

  # Audio for thunder sound
  audioplayers: ^6.1.0

  # Local storage for user preferences
  shared_preferences: ^2.0.0
  flutter_dotenv: ^5.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
